### ISSUE TITLE
open source checklist

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton-go-driver#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- [ ] test/fix it to make sure it works with latest proton, with default branch(develop)
- [ ] update README, which port it connects and how to use it
- [ ] generate binary or install via source go get -u [github.com/timeplus-io/proton-go-driver](http://github.com/timeplus-io/proton-go-driver)?

**Describe alternatives you've considered**

**Additional context**

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.

**Comment by jovezhong** [comment]
(Jove Github Bot) assuming it is not done, deferred this ticket to the next sprint.
